if(EXISTS "/mnt/c/Users/Lucius Nwakamma/QuantLab/build-wsl/tests/cpp/test_order_book[1]_tests.cmake")
  include("/mnt/c/Users/Lucius Nwakamma/QuantLab/build-wsl/tests/cpp/test_order_book[1]_tests.cmake")
else()
  add_test(test_order_book_NOT_BUILT test_order_book_NOT_BUILT)
endif()
