#pragma once
#include "common/types.hpp"
#include <vector>
#include <functional>
#include <string>

namespace quantlab::backtester {

struct BacktestConfig {
    Timestamp   start;
    Timestamp   end;
    double      initial_capital{1'000'000.0};
    std::string resolution{"1d"};     // "tick", "1m", "5m", "1h", "1d"

    // Realistic cost modeling
    double commission_per_share{0.005};
    double commission_min{1.0};
    double slippage_bps{2.0};         // basis points
    double bid_ask_half_spread_bps{1.0};
    double market_impact_coeff{0.1};  // sqrt(qty/adv) * coeff
    double latency_ms{50.0};
    bool   allow_partial_fills{true};
};

struct BacktestTrade {
    Timestamp timestamp;
    Symbol    symbol;
    Side      side;
    Price     fill_price;
    Quantity  quantity;
    double    commission;
    double    slippage;
};

struct BacktestResult {
    double total_return{0.0};
    double annualized_return{0.0};
    double sharpe_ratio{0.0};
    double sortino_ratio{0.0};
    double calmar_ratio{0.0};
    double max_drawdown{0.0};
    double win_rate{0.0};
    double profit_factor{0.0};
    double total_commission{0.0};
    double total_slippage{0.0};
    int    total_trades{0};
    std::vector<double> equity_curve;
    std::vector<double> daily_returns;
    std::vector<BacktestTrade> trades;
};

// Signal generated by a strategy
struct Signal {
    Timestamp timestamp;
    Symbol    symbol;
    double    strength{0.0};  // [-1, 1]: negative = short, positive = long
    double    target_weight{0.0};
};

using StrategyFn = std::function<std::vector<Signal>(
    const std::vector<Bar>& history,
    const std::unordered_map<Symbol, double>& current_weights)>;

class Backtester {
public:
    explicit Backtester(BacktestConfig config);

    void add_data(const Symbol& symbol, std::vector<Bar> bars);
    void set_strategy(StrategyFn strategy);

    BacktestResult run();

    // Walk-forward analysis
    std::vector<BacktestResult> walk_forward(int train_periods, int test_periods);

    // Monte Carlo
    std::vector<BacktestResult> monte_carlo(int simulations, unsigned int seed = 42);

private:
    BacktestConfig                           config_;
    std::unordered_map<Symbol, std::vector<Bar>> data_;
    StrategyFn                               strategy_;

    double apply_costs(Side side, Price price, Quantity qty,
                       double adv, BacktestTrade& trade);
    BacktestResult compute_metrics(const std::vector<double>& equity_curve,
                                   const std::vector<BacktestTrade>& trades) const;
};

} // namespace quantlab::backtester
